/**
 * ISO lookups — country & currency reference data so the admin UI can let
 * sellers type "Morocco" instead of "MA" while the DB still stores the
 * 2-letter ISO 3166-1 alpha-2 code (brain.py's libphonenumber-based country
 * detection emits codes, so the bot side has to match codes too).
 */

export type Country = {
  code: string;       // ISO 3166-1 alpha-2
  name: string;
  flag?: string;      // emoji flag for nicer dropdowns
  default_currency?: string;
  default_language?: string;
};

// Curated list — all sovereign states + key territories (~250 entries).
// Sorted alphabetically by name for the datalist dropdown.
export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan',          flag: '🇦🇫', default_currency: 'AFN', default_language: 'fa' },
  { code: 'AL', name: 'Albania',              flag: '🇦🇱', default_currency: 'ALL', default_language: 'sq' },
  { code: 'DZ', name: 'Algeria',              flag: '🇩🇿', default_currency: 'DZD', default_language: 'ar' },
  { code: 'AD', name: 'Andorra',              flag: '🇦🇩', default_currency: 'EUR', default_language: 'ca' },
  { code: 'AO', name: 'Angola',               flag: '🇦🇴', default_currency: 'AOA', default_language: 'pt' },
  { code: 'AR', name: 'Argentina',            flag: '🇦🇷', default_currency: 'ARS', default_language: 'es' },
  { code: 'AM', name: 'Armenia',              flag: '🇦🇲', default_currency: 'AMD', default_language: 'hy' },
  { code: 'AU', name: 'Australia',            flag: '🇦🇺', default_currency: 'AUD', default_language: 'en' },
  { code: 'AT', name: 'Austria',              flag: '🇦🇹', default_currency: 'EUR', default_language: 'de' },
  { code: 'AZ', name: 'Azerbaijan',           flag: '🇦🇿', default_currency: 'AZN', default_language: 'az' },
  { code: 'BH', name: 'Bahrain',              flag: '🇧🇭', default_currency: 'BHD', default_language: 'ar' },
  { code: 'BD', name: 'Bangladesh',           flag: '🇧🇩', default_currency: 'BDT', default_language: 'bn' },
  { code: 'BY', name: 'Belarus',              flag: '🇧🇾', default_currency: 'BYN', default_language: 'be' },
  { code: 'BE', name: 'Belgium',              flag: '🇧🇪', default_currency: 'EUR', default_language: 'fr' },
  { code: 'BJ', name: 'Benin',                flag: '🇧🇯', default_currency: 'XOF', default_language: 'fr' },
  { code: 'BO', name: 'Bolivia',              flag: '🇧🇴', default_currency: 'BOB', default_language: 'es' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', default_currency: 'BAM', default_language: 'bs' },
  { code: 'BW', name: 'Botswana',             flag: '🇧🇼', default_currency: 'BWP', default_language: 'en' },
  { code: 'BR', name: 'Brazil',               flag: '🇧🇷', default_currency: 'BRL', default_language: 'pt' },
  { code: 'BG', name: 'Bulgaria',             flag: '🇧🇬', default_currency: 'BGN', default_language: 'bg' },
  { code: 'BF', name: 'Burkina Faso',         flag: '🇧🇫', default_currency: 'XOF', default_language: 'fr' },
  { code: 'BI', name: 'Burundi',              flag: '🇧🇮', default_currency: 'BIF', default_language: 'fr' },
  { code: 'KH', name: 'Cambodia',             flag: '🇰🇭', default_currency: 'KHR', default_language: 'km' },
  { code: 'CM', name: 'Cameroon',             flag: '🇨🇲', default_currency: 'XAF', default_language: 'fr' },
  { code: 'CA', name: 'Canada',               flag: '🇨🇦', default_currency: 'CAD', default_language: 'en' },
  { code: 'CV', name: 'Cape Verde',           flag: '🇨🇻', default_currency: 'CVE', default_language: 'pt' },
  { code: 'TD', name: 'Chad',                 flag: '🇹🇩', default_currency: 'XAF', default_language: 'fr' },
  { code: 'CL', name: 'Chile',                flag: '🇨🇱', default_currency: 'CLP', default_language: 'es' },
  { code: 'CN', name: 'China',                flag: '🇨🇳', default_currency: 'CNY', default_language: 'zh' },
  { code: 'CO', name: 'Colombia',             flag: '🇨🇴', default_currency: 'COP', default_language: 'es' },
  { code: 'KM', name: 'Comoros',              flag: '🇰🇲', default_currency: 'KMF', default_language: 'ar' },
  { code: 'CG', name: 'Congo',                flag: '🇨🇬', default_currency: 'XAF', default_language: 'fr' },
  { code: 'CD', name: 'Congo (DRC)',          flag: '🇨🇩', default_currency: 'CDF', default_language: 'fr' },
  { code: 'CR', name: 'Costa Rica',           flag: '🇨🇷', default_currency: 'CRC', default_language: 'es' },
  { code: 'CI', name: "Côte d'Ivoire",        flag: '🇨🇮', default_currency: 'XOF', default_language: 'fr' },
  { code: 'HR', name: 'Croatia',              flag: '🇭🇷', default_currency: 'EUR', default_language: 'hr' },
  { code: 'CU', name: 'Cuba',                 flag: '🇨🇺', default_currency: 'CUP', default_language: 'es' },
  { code: 'CY', name: 'Cyprus',               flag: '🇨🇾', default_currency: 'EUR', default_language: 'el' },
  { code: 'CZ', name: 'Czech Republic',       flag: '🇨🇿', default_currency: 'CZK', default_language: 'cs' },
  { code: 'DK', name: 'Denmark',              flag: '🇩🇰', default_currency: 'DKK', default_language: 'da' },
  { code: 'DJ', name: 'Djibouti',             flag: '🇩🇯', default_currency: 'DJF', default_language: 'ar' },
  { code: 'DO', name: 'Dominican Republic',   flag: '🇩🇴', default_currency: 'DOP', default_language: 'es' },
  { code: 'EC', name: 'Ecuador',              flag: '🇪🇨', default_currency: 'USD', default_language: 'es' },
  { code: 'EG', name: 'Egypt',                flag: '🇪🇬', default_currency: 'EGP', default_language: 'ar' },
  { code: 'SV', name: 'El Salvador',          flag: '🇸🇻', default_currency: 'USD', default_language: 'es' },
  { code: 'GQ', name: 'Equatorial Guinea',    flag: '🇬🇶', default_currency: 'XAF', default_language: 'es' },
  { code: 'ER', name: 'Eritrea',              flag: '🇪🇷', default_currency: 'ERN', default_language: 'ti' },
  { code: 'EE', name: 'Estonia',              flag: '🇪🇪', default_currency: 'EUR', default_language: 'et' },
  { code: 'ET', name: 'Ethiopia',             flag: '🇪🇹', default_currency: 'ETB', default_language: 'am' },
  { code: 'FI', name: 'Finland',              flag: '🇫🇮', default_currency: 'EUR', default_language: 'fi' },
  { code: 'FR', name: 'France',               flag: '🇫🇷', default_currency: 'EUR', default_language: 'fr' },
  { code: 'GA', name: 'Gabon',                flag: '🇬🇦', default_currency: 'XAF', default_language: 'fr' },
  { code: 'GM', name: 'Gambia',               flag: '🇬🇲', default_currency: 'GMD', default_language: 'en' },
  { code: 'GE', name: 'Georgia',              flag: '🇬🇪', default_currency: 'GEL', default_language: 'ka' },
  { code: 'DE', name: 'Germany',              flag: '🇩🇪', default_currency: 'EUR', default_language: 'de' },
  { code: 'GH', name: 'Ghana',                flag: '🇬🇭', default_currency: 'GHS', default_language: 'en' },
  { code: 'GR', name: 'Greece',               flag: '🇬🇷', default_currency: 'EUR', default_language: 'el' },
  { code: 'GT', name: 'Guatemala',            flag: '🇬🇹', default_currency: 'GTQ', default_language: 'es' },
  { code: 'GN', name: 'Guinea',               flag: '🇬🇳', default_currency: 'GNF', default_language: 'fr' },
  { code: 'GW', name: 'Guinea-Bissau',        flag: '🇬🇼', default_currency: 'XOF', default_language: 'pt' },
  { code: 'HT', name: 'Haiti',                flag: '🇭🇹', default_currency: 'HTG', default_language: 'fr' },
  { code: 'HN', name: 'Honduras',             flag: '🇭🇳', default_currency: 'HNL', default_language: 'es' },
  { code: 'HK', name: 'Hong Kong',            flag: '🇭🇰', default_currency: 'HKD', default_language: 'zh' },
  { code: 'HU', name: 'Hungary',              flag: '🇭🇺', default_currency: 'HUF', default_language: 'hu' },
  { code: 'IS', name: 'Iceland',              flag: '🇮🇸', default_currency: 'ISK', default_language: 'is' },
  { code: 'IN', name: 'India',                flag: '🇮🇳', default_currency: 'INR', default_language: 'hi' },
  { code: 'ID', name: 'Indonesia',            flag: '🇮🇩', default_currency: 'IDR', default_language: 'id' },
  { code: 'IR', name: 'Iran',                 flag: '🇮🇷', default_currency: 'IRR', default_language: 'fa' },
  { code: 'IQ', name: 'Iraq',                 flag: '🇮🇶', default_currency: 'IQD', default_language: 'ar' },
  { code: 'IE', name: 'Ireland',              flag: '🇮🇪', default_currency: 'EUR', default_language: 'en' },
  { code: 'IL', name: 'Israel',               flag: '🇮🇱', default_currency: 'ILS', default_language: 'he' },
  { code: 'IT', name: 'Italy',                flag: '🇮🇹', default_currency: 'EUR', default_language: 'it' },
  { code: 'JM', name: 'Jamaica',              flag: '🇯🇲', default_currency: 'JMD', default_language: 'en' },
  { code: 'JP', name: 'Japan',                flag: '🇯🇵', default_currency: 'JPY', default_language: 'ja' },
  { code: 'JO', name: 'Jordan',               flag: '🇯🇴', default_currency: 'JOD', default_language: 'ar' },
  { code: 'KZ', name: 'Kazakhstan',           flag: '🇰🇿', default_currency: 'KZT', default_language: 'kk' },
  { code: 'KE', name: 'Kenya',                flag: '🇰🇪', default_currency: 'KES', default_language: 'en' },
  { code: 'KW', name: 'Kuwait',               flag: '🇰🇼', default_currency: 'KWD', default_language: 'ar' },
  { code: 'KG', name: 'Kyrgyzstan',           flag: '🇰🇬', default_currency: 'KGS', default_language: 'ky' },
  { code: 'LA', name: 'Laos',                 flag: '🇱🇦', default_currency: 'LAK', default_language: 'lo' },
  { code: 'LV', name: 'Latvia',               flag: '🇱🇻', default_currency: 'EUR', default_language: 'lv' },
  { code: 'LB', name: 'Lebanon',              flag: '🇱🇧', default_currency: 'LBP', default_language: 'ar' },
  { code: 'LS', name: 'Lesotho',              flag: '🇱🇸', default_currency: 'LSL', default_language: 'en' },
  { code: 'LR', name: 'Liberia',              flag: '🇱🇷', default_currency: 'LRD', default_language: 'en' },
  { code: 'LY', name: 'Libya',                flag: '🇱🇾', default_currency: 'LYD', default_language: 'ar' },
  { code: 'LT', name: 'Lithuania',            flag: '🇱🇹', default_currency: 'EUR', default_language: 'lt' },
  { code: 'LU', name: 'Luxembourg',           flag: '🇱🇺', default_currency: 'EUR', default_language: 'fr' },
  { code: 'MG', name: 'Madagascar',           flag: '🇲🇬', default_currency: 'MGA', default_language: 'fr' },
  { code: 'MW', name: 'Malawi',               flag: '🇲🇼', default_currency: 'MWK', default_language: 'en' },
  { code: 'MY', name: 'Malaysia',             flag: '🇲🇾', default_currency: 'MYR', default_language: 'ms' },
  { code: 'ML', name: 'Mali',                 flag: '🇲🇱', default_currency: 'XOF', default_language: 'fr' },
  { code: 'MT', name: 'Malta',                flag: '🇲🇹', default_currency: 'EUR', default_language: 'mt' },
  { code: 'MR', name: 'Mauritania',           flag: '🇲🇷', default_currency: 'MRU', default_language: 'ar' },
  { code: 'MU', name: 'Mauritius',            flag: '🇲🇺', default_currency: 'MUR', default_language: 'en' },
  { code: 'MX', name: 'Mexico',               flag: '🇲🇽', default_currency: 'MXN', default_language: 'es' },
  { code: 'MD', name: 'Moldova',              flag: '🇲🇩', default_currency: 'MDL', default_language: 'ro' },
  { code: 'MC', name: 'Monaco',               flag: '🇲🇨', default_currency: 'EUR', default_language: 'fr' },
  { code: 'MN', name: 'Mongolia',             flag: '🇲🇳', default_currency: 'MNT', default_language: 'mn' },
  { code: 'ME', name: 'Montenegro',           flag: '🇲🇪', default_currency: 'EUR', default_language: 'sr' },
  { code: 'MA', name: 'Morocco',              flag: '🇲🇦', default_currency: 'MAD', default_language: 'ar' },
  { code: 'MZ', name: 'Mozambique',           flag: '🇲🇿', default_currency: 'MZN', default_language: 'pt' },
  { code: 'MM', name: 'Myanmar',              flag: '🇲🇲', default_currency: 'MMK', default_language: 'my' },
  { code: 'NA', name: 'Namibia',              flag: '🇳🇦', default_currency: 'NAD', default_language: 'en' },
  { code: 'NP', name: 'Nepal',                flag: '🇳🇵', default_currency: 'NPR', default_language: 'ne' },
  { code: 'NL', name: 'Netherlands',          flag: '🇳🇱', default_currency: 'EUR', default_language: 'nl' },
  { code: 'NZ', name: 'New Zealand',          flag: '🇳🇿', default_currency: 'NZD', default_language: 'en' },
  { code: 'NI', name: 'Nicaragua',            flag: '🇳🇮', default_currency: 'NIO', default_language: 'es' },
  { code: 'NE', name: 'Niger',                flag: '🇳🇪', default_currency: 'XOF', default_language: 'fr' },
  { code: 'NG', name: 'Nigeria',              flag: '🇳🇬', default_currency: 'NGN', default_language: 'en' },
  { code: 'KP', name: 'North Korea',          flag: '🇰🇵', default_currency: 'KPW', default_language: 'ko' },
  { code: 'MK', name: 'North Macedonia',      flag: '🇲🇰', default_currency: 'MKD', default_language: 'mk' },
  { code: 'NO', name: 'Norway',               flag: '🇳🇴', default_currency: 'NOK', default_language: 'no' },
  { code: 'OM', name: 'Oman',                 flag: '🇴🇲', default_currency: 'OMR', default_language: 'ar' },
  { code: 'PK', name: 'Pakistan',             flag: '🇵🇰', default_currency: 'PKR', default_language: 'ur' },
  { code: 'PS', name: 'Palestine',            flag: '🇵🇸', default_currency: 'ILS', default_language: 'ar' },
  { code: 'PA', name: 'Panama',               flag: '🇵🇦', default_currency: 'USD', default_language: 'es' },
  { code: 'PY', name: 'Paraguay',             flag: '🇵🇾', default_currency: 'PYG', default_language: 'es' },
  { code: 'PE', name: 'Peru',                 flag: '🇵🇪', default_currency: 'PEN', default_language: 'es' },
  { code: 'PH', name: 'Philippines',          flag: '🇵🇭', default_currency: 'PHP', default_language: 'en' },
  { code: 'PL', name: 'Poland',               flag: '🇵🇱', default_currency: 'PLN', default_language: 'pl' },
  { code: 'PT', name: 'Portugal',             flag: '🇵🇹', default_currency: 'EUR', default_language: 'pt' },
  { code: 'PR', name: 'Puerto Rico',          flag: '🇵🇷', default_currency: 'USD', default_language: 'es' },
  { code: 'QA', name: 'Qatar',                flag: '🇶🇦', default_currency: 'QAR', default_language: 'ar' },
  { code: 'RO', name: 'Romania',              flag: '🇷🇴', default_currency: 'RON', default_language: 'ro' },
  { code: 'RU', name: 'Russia',               flag: '🇷🇺', default_currency: 'RUB', default_language: 'ru' },
  { code: 'RW', name: 'Rwanda',               flag: '🇷🇼', default_currency: 'RWF', default_language: 'en' },
  { code: 'SA', name: 'Saudi Arabia',         flag: '🇸🇦', default_currency: 'SAR', default_language: 'ar' },
  { code: 'SN', name: 'Senegal',              flag: '🇸🇳', default_currency: 'XOF', default_language: 'fr' },
  { code: 'RS', name: 'Serbia',               flag: '🇷🇸', default_currency: 'RSD', default_language: 'sr' },
  { code: 'SC', name: 'Seychelles',           flag: '🇸🇨', default_currency: 'SCR', default_language: 'en' },
  { code: 'SL', name: 'Sierra Leone',         flag: '🇸🇱', default_currency: 'SLL', default_language: 'en' },
  { code: 'SG', name: 'Singapore',            flag: '🇸🇬', default_currency: 'SGD', default_language: 'en' },
  { code: 'SK', name: 'Slovakia',             flag: '🇸🇰', default_currency: 'EUR', default_language: 'sk' },
  { code: 'SI', name: 'Slovenia',             flag: '🇸🇮', default_currency: 'EUR', default_language: 'sl' },
  { code: 'SO', name: 'Somalia',              flag: '🇸🇴', default_currency: 'SOS', default_language: 'so' },
  { code: 'ZA', name: 'South Africa',         flag: '🇿🇦', default_currency: 'ZAR', default_language: 'en' },
  { code: 'KR', name: 'South Korea',          flag: '🇰🇷', default_currency: 'KRW', default_language: 'ko' },
  { code: 'SS', name: 'South Sudan',          flag: '🇸🇸', default_currency: 'SSP', default_language: 'en' },
  { code: 'ES', name: 'Spain',                flag: '🇪🇸', default_currency: 'EUR', default_language: 'es' },
  { code: 'LK', name: 'Sri Lanka',            flag: '🇱🇰', default_currency: 'LKR', default_language: 'si' },
  { code: 'SD', name: 'Sudan',                flag: '🇸🇩', default_currency: 'SDG', default_language: 'ar' },
  { code: 'SR', name: 'Suriname',             flag: '🇸🇷', default_currency: 'SRD', default_language: 'nl' },
  { code: 'SE', name: 'Sweden',               flag: '🇸🇪', default_currency: 'SEK', default_language: 'sv' },
  { code: 'CH', name: 'Switzerland',          flag: '🇨🇭', default_currency: 'CHF', default_language: 'de' },
  { code: 'SY', name: 'Syria',                flag: '🇸🇾', default_currency: 'SYP', default_language: 'ar' },
  { code: 'TW', name: 'Taiwan',               flag: '🇹🇼', default_currency: 'TWD', default_language: 'zh' },
  { code: 'TJ', name: 'Tajikistan',           flag: '🇹🇯', default_currency: 'TJS', default_language: 'tg' },
  { code: 'TZ', name: 'Tanzania',             flag: '🇹🇿', default_currency: 'TZS', default_language: 'sw' },
  { code: 'TH', name: 'Thailand',             flag: '🇹🇭', default_currency: 'THB', default_language: 'th' },
  { code: 'TG', name: 'Togo',                 flag: '🇹🇬', default_currency: 'XOF', default_language: 'fr' },
  { code: 'TT', name: 'Trinidad and Tobago',  flag: '🇹🇹', default_currency: 'TTD', default_language: 'en' },
  { code: 'TN', name: 'Tunisia',              flag: '🇹🇳', default_currency: 'TND', default_language: 'ar' },
  { code: 'TR', name: 'Turkey',               flag: '🇹🇷', default_currency: 'TRY', default_language: 'tr' },
  { code: 'TM', name: 'Turkmenistan',         flag: '🇹🇲', default_currency: 'TMT', default_language: 'tk' },
  { code: 'UG', name: 'Uganda',               flag: '🇺🇬', default_currency: 'UGX', default_language: 'en' },
  { code: 'UA', name: 'Ukraine',              flag: '🇺🇦', default_currency: 'UAH', default_language: 'uk' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', default_currency: 'AED', default_language: 'ar' },
  { code: 'GB', name: 'United Kingdom',       flag: '🇬🇧', default_currency: 'GBP', default_language: 'en' },
  { code: 'US', name: 'United States',        flag: '🇺🇸', default_currency: 'USD', default_language: 'en' },
  { code: 'UY', name: 'Uruguay',              flag: '🇺🇾', default_currency: 'UYU', default_language: 'es' },
  { code: 'UZ', name: 'Uzbekistan',           flag: '🇺🇿', default_currency: 'UZS', default_language: 'uz' },
  { code: 'VE', name: 'Venezuela',            flag: '🇻🇪', default_currency: 'VES', default_language: 'es' },
  { code: 'VN', name: 'Vietnam',              flag: '🇻🇳', default_currency: 'VND', default_language: 'vi' },
  { code: 'YE', name: 'Yemen',                flag: '🇾🇪', default_currency: 'YER', default_language: 'ar' },
  { code: 'ZM', name: 'Zambia',               flag: '🇿🇲', default_currency: 'ZMW', default_language: 'en' },
  { code: 'ZW', name: 'Zimbabwe',             flag: '🇿🇼', default_currency: 'ZWL', default_language: 'en' },
];

export type Currency = {
  code: string;      // ISO 4217
  name: string;
  symbol: string;
};

// Common currencies — used only as autocomplete hints for the seller's
// currency input. The input itself is free-text, so anything not in this
// list still works. Sorted by ISO code for easier scanning when typing.
export const CURRENCIES: Currency[] = [
  { code: 'AED', name: 'UAE Dirham',                     symbol: 'AED' },
  { code: 'AFN', name: 'Afghan Afghani',                 symbol: '؋' },
  { code: 'ALL', name: 'Albanian Lek',                   symbol: 'L' },
  { code: 'AMD', name: 'Armenian Dram',                  symbol: '֏' },
  { code: 'AOA', name: 'Angolan Kwanza',                 symbol: 'Kz' },
  { code: 'ARS', name: 'Argentine Peso',                 symbol: 'AR$' },
  { code: 'AUD', name: 'Australian Dollar',              symbol: 'A$' },
  { code: 'AZN', name: 'Azerbaijani Manat',              symbol: '₼' },
  { code: 'BAM', name: 'Bosnia Convertible Mark',        symbol: 'KM' },
  { code: 'BDT', name: 'Bangladeshi Taka',               symbol: '৳' },
  { code: 'BGN', name: 'Bulgarian Lev',                  symbol: 'лв' },
  { code: 'BHD', name: 'Bahraini Dinar',                 symbol: 'BD' },
  { code: 'BIF', name: 'Burundi Franc',                  symbol: 'FBu' },
  { code: 'BOB', name: 'Bolivian Boliviano',             symbol: 'Bs' },
  { code: 'BRL', name: 'Brazilian Real',                 symbol: 'R$' },
  { code: 'BWP', name: 'Botswana Pula',                  symbol: 'P' },
  { code: 'BYN', name: 'Belarus Ruble',                  symbol: 'Br' },
  { code: 'CAD', name: 'Canadian Dollar',                symbol: 'C$' },
  { code: 'CDF', name: 'Congolese Franc',                symbol: 'FC' },
  { code: 'CHF', name: 'Swiss Franc',                    symbol: 'Fr' },
  { code: 'CLP', name: 'Chilean Peso',                   symbol: 'CLP$' },
  { code: 'CNY', name: 'Chinese Yuan',                   symbol: '¥' },
  { code: 'COP', name: 'Colombian Peso',                 symbol: 'CO$' },
  { code: 'CRC', name: 'Costa Rican Colon',              symbol: '₡' },
  { code: 'CUP', name: 'Cuban Peso',                     symbol: '₱' },
  { code: 'CVE', name: 'Cape Verde Escudo',              symbol: '$' },
  { code: 'CZK', name: 'Czech Koruna',                   symbol: 'Kč' },
  { code: 'DJF', name: 'Djibouti Franc',                 symbol: 'Fdj' },
  { code: 'DKK', name: 'Danish Krone',                   symbol: 'kr' },
  { code: 'DOP', name: 'Dominican Peso',                 symbol: 'RD$' },
  { code: 'DZD', name: 'Algerian Dinar',                 symbol: 'DA' },
  { code: 'EGP', name: 'Egyptian Pound',                 symbol: 'E£' },
  { code: 'ERN', name: 'Eritrean Nakfa',                 symbol: 'Nfk' },
  { code: 'ETB', name: 'Ethiopian Birr',                 symbol: 'Br' },
  { code: 'EUR', name: 'Euro',                           symbol: '€' },
  { code: 'GBP', name: 'British Pound',                  symbol: '£' },
  { code: 'GEL', name: 'Georgian Lari',                  symbol: '₾' },
  { code: 'GHS', name: 'Ghanaian Cedi',                  symbol: '₵' },
  { code: 'GMD', name: 'Gambian Dalasi',                 symbol: 'D' },
  { code: 'GNF', name: 'Guinean Franc',                  symbol: 'FG' },
  { code: 'GTQ', name: 'Guatemalan Quetzal',             symbol: 'Q' },
  { code: 'HKD', name: 'Hong Kong Dollar',               symbol: 'HK$' },
  { code: 'HNL', name: 'Honduran Lempira',               symbol: 'L' },
  { code: 'HTG', name: 'Haitian Gourde',                 symbol: 'G' },
  { code: 'HUF', name: 'Hungarian Forint',               symbol: 'Ft' },
  { code: 'IDR', name: 'Indonesian Rupiah',              symbol: 'Rp' },
  { code: 'ILS', name: 'Israeli Shekel',                 symbol: '₪' },
  { code: 'INR', name: 'Indian Rupee',                   symbol: '₹' },
  { code: 'IQD', name: 'Iraqi Dinar',                    symbol: 'ID' },
  { code: 'IRR', name: 'Iranian Rial',                   symbol: '﷼' },
  { code: 'ISK', name: 'Icelandic Krona',                symbol: 'kr' },
  { code: 'JMD', name: 'Jamaican Dollar',                symbol: 'J$' },
  { code: 'JOD', name: 'Jordanian Dinar',                symbol: 'JD' },
  { code: 'JPY', name: 'Japanese Yen',                   symbol: '¥' },
  { code: 'KES', name: 'Kenyan Shilling',                symbol: 'KSh' },
  { code: 'KGS', name: 'Kyrgyzstani Som',                symbol: 'с' },
  { code: 'KHR', name: 'Cambodian Riel',                 symbol: '៛' },
  { code: 'KMF', name: 'Comoros Franc',                  symbol: 'CF' },
  { code: 'KRW', name: 'South Korean Won',               symbol: '₩' },
  { code: 'KWD', name: 'Kuwaiti Dinar',                  symbol: 'KD' },
  { code: 'KZT', name: 'Kazakhstani Tenge',              symbol: '₸' },
  { code: 'LAK', name: 'Laotian Kip',                    symbol: '₭' },
  { code: 'LBP', name: 'Lebanese Pound',                 symbol: 'L£' },
  { code: 'LKR', name: 'Sri Lankan Rupee',               symbol: 'LKR' },
  { code: 'LRD', name: 'Liberian Dollar',                symbol: 'L$' },
  { code: 'LSL', name: 'Lesotho Loti',                   symbol: 'L' },
  { code: 'LYD', name: 'Libyan Dinar',                   symbol: 'LD' },
  { code: 'MAD', name: 'Moroccan Dirham',                symbol: 'DH' },
  { code: 'MDL', name: 'Moldovan Leu',                   symbol: 'L' },
  { code: 'MGA', name: 'Malagasy Ariary',                symbol: 'Ar' },
  { code: 'MKD', name: 'Macedonian Denar',               symbol: 'ден' },
  { code: 'MMK', name: 'Myanmar Kyat',                   symbol: 'K' },
  { code: 'MNT', name: 'Mongolian Tugrik',               symbol: '₮' },
  { code: 'MRU', name: 'Mauritanian Ouguiya',            symbol: 'UM' },
  { code: 'MUR', name: 'Mauritian Rupee',                symbol: '₨' },
  { code: 'MWK', name: 'Malawi Kwacha',                  symbol: 'MK' },
  { code: 'MXN', name: 'Mexican Peso',                   symbol: 'Mex$' },
  { code: 'MYR', name: 'Malaysian Ringgit',              symbol: 'RM' },
  { code: 'MZN', name: 'Mozambican Metical',             symbol: 'MT' },
  { code: 'NAD', name: 'Namibian Dollar',                symbol: 'N$' },
  { code: 'NGN', name: 'Nigerian Naira',                 symbol: '₦' },
  { code: 'NIO', name: 'Nicaraguan Cordoba',             symbol: 'C$' },
  { code: 'NOK', name: 'Norwegian Krone',                symbol: 'kr' },
  { code: 'NPR', name: 'Nepalese Rupee',                 symbol: '₨' },
  { code: 'NZD', name: 'New Zealand Dollar',             symbol: 'NZ$' },
  { code: 'OMR', name: 'Omani Rial',                     symbol: '﷼' },
  { code: 'PEN', name: 'Peruvian Sol',                   symbol: 'S/' },
  { code: 'PHP', name: 'Philippine Peso',                symbol: '₱' },
  { code: 'PKR', name: 'Pakistani Rupee',                symbol: '₨' },
  { code: 'PLN', name: 'Polish Zloty',                   symbol: 'zł' },
  { code: 'PYG', name: 'Paraguayan Guarani',             symbol: '₲' },
  { code: 'QAR', name: 'Qatari Riyal',                   symbol: '﷼' },
  { code: 'RON', name: 'Romanian Leu',                   symbol: 'lei' },
  { code: 'RSD', name: 'Serbian Dinar',                  symbol: 'дин' },
  { code: 'RUB', name: 'Russian Ruble',                  symbol: '₽' },
  { code: 'RWF', name: 'Rwandan Franc',                  symbol: 'FRw' },
  { code: 'SAR', name: 'Saudi Riyal',                    symbol: '﷼' },
  { code: 'SCR', name: 'Seychelles Rupee',               symbol: '₨' },
  { code: 'SDG', name: 'Sudanese Pound',                 symbol: 'ج.س' },
  { code: 'SEK', name: 'Swedish Krona',                  symbol: 'kr' },
  { code: 'SGD', name: 'Singapore Dollar',               symbol: 'S$' },
  { code: 'SLL', name: 'Sierra Leonean Leone',           symbol: 'Le' },
  { code: 'SOS', name: 'Somali Shilling',                symbol: 'Sh' },
  { code: 'SRD', name: 'Surinamese Dollar',              symbol: 'Sr$' },
  { code: 'SYP', name: 'Syrian Pound',                   symbol: 'S£' },
  { code: 'THB', name: 'Thai Baht',                      symbol: '฿' },
  { code: 'TJS', name: 'Tajikistani Somoni',             symbol: 'SM' },
  { code: 'TMT', name: 'Turkmenistan Manat',             symbol: 'm' },
  { code: 'TND', name: 'Tunisian Dinar',                 symbol: 'DT' },
  { code: 'TRY', name: 'Turkish Lira',                   symbol: '₺' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar',       symbol: 'TT$' },
  { code: 'TWD', name: 'Taiwan Dollar',                  symbol: 'NT$' },
  { code: 'TZS', name: 'Tanzanian Shilling',             symbol: 'TSh' },
  { code: 'UAH', name: 'Ukrainian Hryvnia',              symbol: '₴' },
  { code: 'UGX', name: 'Ugandan Shilling',               symbol: 'USh' },
  { code: 'USD', name: 'US Dollar',                      symbol: '$' },
  { code: 'UYU', name: 'Uruguayan Peso',                 symbol: '$U' },
  { code: 'UZS', name: 'Uzbekistani Som',                symbol: 'soʻm' },
  { code: 'VES', name: 'Venezuelan Bolivar',             symbol: 'Bs.' },
  { code: 'VND', name: 'Vietnamese Dong',                symbol: '₫' },
  { code: 'XAF', name: 'Central African CFA Franc',      symbol: 'FCFA' },
  { code: 'XOF', name: 'West African CFA Franc',         symbol: 'CFA' },
  { code: 'YER', name: 'Yemeni Rial',                    symbol: '﷼' },
  { code: 'ZAR', name: 'South African Rand',             symbol: 'R' },
  { code: 'ZMW', name: 'Zambian Kwacha',                 symbol: 'ZK' },
  { code: 'ZWL', name: 'Zimbabwean Dollar',              symbol: 'Z$' },
];

// Quick lookup helpers — used by the AdminProductEditor's country/currency inputs.

export function findCountryByCode(code: string): Country | undefined {
  if (!code) return undefined;
  const up = code.toUpperCase();
  return COUNTRIES.find(c => c.code === up);
}

export function findCountryByName(name: string): Country | undefined {
  if (!name) return undefined;
  const lower = name.trim().toLowerCase();
  return COUNTRIES.find(c => c.name.toLowerCase() === lower);
}

/** Best-effort: matches by exact code, exact name, or unique prefix. */
export function resolveCountry(input: string): Country | undefined {
  if (!input) return undefined;
  const t = input.trim();
  if (t.length === 2) {
    const byCode = findCountryByCode(t);
    if (byCode) return byCode;
  }
  const byName = findCountryByName(t);
  if (byName) return byName;
  const lower = t.toLowerCase();
  const prefixHits = COUNTRIES.filter(c => c.name.toLowerCase().startsWith(lower));
  return prefixHits.length === 1 ? prefixHits[0] : undefined;
}

export function findCurrencyByCode(code: string): Currency | undefined {
  if (!code) return undefined;
  return CURRENCIES.find(c => c.code === code.toUpperCase());
}
